services:
  mysql:
    image: mysql:8.0
    container_name: mysql8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./data:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  mysql-data:
    driver: local
